component thc2 "Height Control Up/Down Input";

license "GPLv2 or greater";

option singleton yes;

pin in float encoder_vel "Connect to hm2_7i92.0.encoder.00.velocity";
pin in float volts_requested "Tip Volts current_vel >= min_velocity requested";

pin out bit arc_ok_status "Arc OK status";
pin out bit thcu "THC up";
pin out bit thcd "THC down";

pin out float volts "The Calculated Volts";

function _;

;;

FUNCTION(_) {
    volts = encoder_vel * 0.1;
    if (volts <150 && volts >50){arc_ok_status = 1;}
    else {arc_ok_status = 0;}

    if (volts < volts_requested){thcu = 1;}
    else {thcu = 0;}

    if (volts > volts_requested){thcd = 1;}
    else {thcd = 0;}

}

